export interface BanchoEvent {
    display_html: string;
    beatmap_id: string;
    beatmapset_id: string;
    date: string;
    epicfactor: string;
};

export interface BanchoUser {
    user_id: string;
    username: string;
    join_date: string;
    country: string;
    count300: string;
    count100: string;
    count50: string;
    playcount: string;
    ranked_score: string;
    total_score: string;
    pp_rank: string;
    level: string;
    pp_raw: string;
    accuracy: string;
    count_rank_ss: string;
    count_rank_ssh: string;
    count_rank_s: string;
    count_rank_sh: string;
    count_rank_a: string;
    total_seconds_played: string;
    pp_country_rank: string;
    events: BanchoEvent[];
};

export interface BanchoBeatmap {
    beatmapset_id: string;
    beatmap_id: string;
    creator_id: string;
    file_md5: string;
    tags: string;
    genre_id: string;
    language_id: string;
    artist: string;
    title: string;
    version: string;
    creator: string;
    artist_unicode: string;
    title_unicode: string;
    source: string;
    approved: string;
    submit_date: string;
    approved_date: string;
    last_update: string;
    total_length: string;
    hit_length: string;
    diff_size: string;
    diff_overall: string;
    diff_approach: string;
    diff_drain: string;
    diff_aim: string;
    diff_speed: string;
    difficultyrating: string;
    bpm: string;
    mode: string;
    count_normal: string;
    count_slider: string;
    count_spinner: string;
    favourite_count: string;
    rating: string;
    storyboard: string;
    video: string;
    download_unavailable: string;
    audio_unavailable: string;
    playcount: string;
    passcount: string;
    max_combo: string;
    packs: string;
};
